version: "2"
linters:
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - std-error-handling
  disable:
    - errcheck # TODO: reenable after fixing all existing issues
formatters:
  enable:
    - goimports
